### ISSUE TITLE
SelenoReceivedException : Unexpected error. System.Net.WebException: Unable to connect to the remote server

### ISSUE THREAD

**Issue by gerardbeckerleg** [TestStack/TestStack.Seleno#147]
Hi Guys,
I have a project set up following the get started instructions.
I am running the test with nunit runner.

Runs great but iisexpress and browser are still running when the tests have completed, this did not happen when I was using only Selenium. The browser window would close and I could re-run the test from the nunit runner.

If I close the browser and iisexpress without restarting nunit and re-run the test I get the following error:
If I close the browser and iisexpress from code in the test and re-run I get the same error:

```
KendoMobile.WebTests.Tests.ListViewTests.FindEmployee():
TestStack.Seleno.Configuration.Interceptors.SelenoReceivedException : Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:7055
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
  ----> OpenQA.Selenium.WebDriverException : Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:7055
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
```

The only way not to get the error is to reload the project in nunit.

If I dispose of the SeleonHost with Host.Instance.Dispose() and re-run I get the following error:

```
KendoMobile.WebTests.Tests.ListViewTests.FindEmployee():
System.ObjectDisposedException : Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed.
```

If I close the browser and stop IISExpress with Host.Instance.Application.Browser.Close() and Host.Instance.Application.WebServer.Stop() I get the following error:

```
KendoMobile.WebTests.Tests.ListViewTests.FindEmployee():
TestStack.Seleno.Configuration.Interceptors.SelenoReceivedException : Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:7055
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
  ----> OpenQA.Selenium.WebDriverException : Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:7055
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
```

All these errors are not a problem if I relaod the project in NUnit but I would like to be able to re-run the tests like I could with the vanilla Selenium.

**Comment by deepthiKrishna285** [comment]
hi mates,

am new to selenium world.
am using selenium c# to automate. AUT is hosted in azure . 
currently am facing below error

using 
Selenium.InternetExplorer.WebDriver.3.11.1
IE 11

Message: OpenQA.Selenium.WebDriverException : Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:59752
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)



Any Help please .
Thanks in Advance

**Comment by SrikanthSamala** [comment]
Iam too facing the same issue

**Comment by venu222** [comment]
Facing the same issue..Any solutions?

**Comment by evildrome** [comment]
Same here...

**Comment by tcom111** [comment]
I am too facing the same issue:

please, someone can help me.

this is my error message:

Message : OpenQA.Selenium.WebDriverException : Unexpected error. System.Net.WebException: Impossible de se connecter au serveur distant ---> System.Net.Sockets.SocketException: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée [::1]:51581
   à System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   à System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   à System.Net.HttpWebRequest.GetRequestStream()
   à OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   à OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   à OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   à OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)

Thanks in Advance

**Comment by hemangshahnxt** [comment]
I am facing the same problem. When i run the test locally on my machine it works fine as intended. But when the same code runs in the azure pipeline some of the tests fails with this error:
`OpenQA.Selenium.WebDriverException : Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:56154

at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)

at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)

--- End of inner exception stack trace ---

at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)

at System.Net.HttpWebRequest.GetRequestStream()

at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)

at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)

at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)

at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)

TearDown : OpenQA.Selenium.WebDriverException : A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:56154/session/431bd7d6e4f8d06693a521a631ccb032/screenshot. The status of the exception was ConnectFailure, and the message was: Unable to connect to the remote server

----> System.Net.WebException : Unable to connect to the remote server

----> System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it 127.0.0.1:56154


Stack trace
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByXPath(String xpath)
   at OpenQA.Selenium.By.<>c__DisplayClass19_0.<XPath>b__0(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(By by)
   at OpenQA.Selenium.Support.PageObjects.DefaultElementLocator.LocateElement(IEnumerable`1 bys)
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.get_Element()
   at OpenQA.Selenium.Support.PageObjects.WebElementProxy.Invoke(IMessage msg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at OpenQA.Selenium.IWebElement.SendKeys(String text)
   at PwC.US.EC.Selenium.Tests.Pages.EC.EC_ProjectPlanPage.AssignTo(String username) in H:\us-tax-tech3\_work\5\s\PwC.US.EC.Selenium\PwC.US.EC.Selenium.Tests\Pages\EC\EC_ProjectPlanPage.cs:line 550
   at PwC.US.EC.Selenium.Tests.Tests.HealthCheckTests.Verify_ProjectPlan_DeliverableAndTask() in H:\us-tax-tech3\_work\5\s\PwC.US.EC.Selenium\PwC.US.EC.Selenium.Tests\Tests\HealthCheckTests.cs:line 408
--TearDown
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.GetScreenshot()
   at PwC.US.EC.Selenium.Tests.ReportUtils.Capture(IWebDriver driver, String screenShotName) in H:\us-tax-tech3\_work\5\s\PwC.US.EC.Selenium\PwC.US.EC.Selenium.Tests\Utils\ReportUtils.cs:line 134
   at PwC.US.EC.Selenium.Tests.ReportUtils.UpdateResult(TestContext context, IWebDriver driver) in H:\us-tax-tech3\_work\5\s\PwC.US.EC.Selenium\PwC.US.EC.Selenium.Tests\Utils\ReportUtils.cs:line 97
   at PwC.US.EC.Selenium.Tests.BaseTest`1.TearDown() in H:\us-tax-tech3\_work\5\s\PwC.US.EC.Selenium\PwC.US.EC.Selenium.Tests\Tests\BaseTest.cs:line 58
--WebException
   at System.Net.HttpWebRequest.GetResponse()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
--SocketException
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
Hooray! There are no test failures.

Showing filters 1 through 4

Showing filters 1 through 4

Showing filters 1 through 4

Showing filters 1 through 4

Showing filters 1 through 4

Showing filters 1 through 4

`
