### ISSUE TITLE
Getting a crash when the tests start up

### ISSUE THREAD

**Issue by aaronpowell** [TestStack/TestStack.Seleno#175]
I've started experiencing an error on our build infrastructure which sees every test fail and nunit hang, causing octopus to hang (we run our UI tests as an octopus step to verify a deployment).

This is the error I'm seeing:

```
SetUp : System.TypeInitializationException : The type initializer for 'MyClient.UITests.Host' threw an exception.
  ----> Autofac.Core.DependencyResolutionException : An exception was thrown while executing a resolve operation. See the InnerException for details. ---> unknown error: cannot get automation extension
from timeout: Timed out receiving message from renderer: -0.153
  (Session info: chrome=37.0.2062.120)
  (Driver info: chromedriver=2.10.267521,platform=Windows NT 6.3 x86_64) (See inner exception for details.)
  ----> System.InvalidOperationException : unknown error: cannot get automation extension
from timeout: Timed out receiving message from renderer: -0.153
  (Session info: chrome=37.0.2062.120)
  (Driver info: chromedriver=2.10.267521,platform=Windows NT 6.3 x86_64)
TearDown : System.TypeInitializationException : The type initializer for 'MyClient.UITests.Host' threw an exception.
  ----> Autofac.Core.DependencyResolutionException : An exception was thrown while executing a resolve operation. See the InnerException for details. ---> unknown error: cannot get automation extension
from timeout: Timed out receiving message from renderer: -0.153
  (Session info: chrome=37.0.2062.120)
  (Driver info: chromedriver=2.10.267521,platform=Windows NT 6.3 x86_64) (See inner exception for details.)
  ----> System.InvalidOperationException : unknown error: cannot get automation extension
from timeout: Timed out receiving message from renderer: -0.153
  (Session info: chrome=37.0.2062.120)
  (Driver info: chromedriver=2.10.267521,platform=Windows NT 6.3 x86_64) at MyClient.UITests.BaseTestPage.Setup() in c:\TeamCity\buildAgent\work\595bd9a420642936\MyClient\Solution\MyClient.UITests\BaseTestPage.cs:line 16
--DependencyResolutionException
at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters) in c:\ConsoleBuildAgent\work\f035b8dd08e41a61\src\TestStack.Seleno\Extensions\WebDriverExtensions.cs:line 0
at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters) in c:\ConsoleBuildAgent\work\f035b8dd08e41a61\src\TestStack.Seleno\Extensions\WebDriverExtensions.cs:line 0
at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters) in c:\ConsoleBuildAgent\work\f035b8dd08e41a61\src\TestStack.Seleno\Extensions\WebDriverExtensions.cs:line 0
at TestStack.Seleno.Configuration.AppConfigurator.CreateApplication() in c:\ConsoleBuildAgent\work\f035b8dd08e41a61\src\TestStack.Seleno\Configuration\AppConfigurator.cs:line 48
at TestStack.Seleno.Configuration.SelenoHost.Run(Action`1 configure) in c:\ConsoleBuildAgent\work\f035b8dd08e41a61\src\TestStack.Seleno\Configuration\SelenoHost.cs:line 83
--InvalidOperationException
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at MyClient.UITests.Host.PickWebDriver() in c:\TeamCity\buildAgent\work\595bd9a420642936\MyClient\Solution\MyClient.UITests\Host.cs:line 64
at System.Lazy`1.CreateValue()
at System.Lazy`1.LazyInitValue()
at TestStack.Seleno.Configuration.AppConfigurator.<>c__DisplayClassb.<WithRemoteWebDriver>b__8() in c:\ConsoleBuildAgent\work\f035b8dd08e41a61\src\TestStack.Seleno\Configuration\AppConfigurator.cs:line 84
at TestStack.Seleno.Configuration.AppConfigurator.<>c__DisplayClassf.<WithWebDriver>b__e(IComponentContext c) in c:\ConsoleBuildAgent\work\f035b8dd08e41a61\src\TestStack.Seleno\Configuration\AppConfigurator.cs:line 103
at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass1`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p) in c:\ConsoleBuildAgent\work\f035b8dd08e41a61\src\TestStack.Seleno\Extensions\WebDriverExtensions.cs:line 0
at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\ConsoleBuildAgent\work\f035b8dd08e41a61\src\TestStack.Seleno\Extensions\WebDriverExtensions.cs:line 0
at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\ConsoleBuildAgent\work\f035b8dd08e41a61\src\TestStack.Seleno\Extensions\WebDriverExtensions.cs:line 0
at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator) in c:\ConsoleBuildAgent\work\f035b8dd08e41a61\src\TestStack.Seleno\Extensions\WebDriverExtensions.cs:line 0
at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\ConsoleBuildAgent\work\f035b8dd08e41a61\src\TestStack.Seleno\Extensions\WebDriverExtensions.cs:line 0
at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\ConsoleBuildAgent\work\f035b8dd08e41a61\src\TestStack.Seleno\Extensions\WebDriverExtensions.cs:line 0
at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters) in c:\ConsoleBuildAgent\work\f035b8dd08e41a61\src\TestStack.Seleno\Extensions\WebDriverExtensions.cs:line 0
--TearDown
at MyClient.UITests.BaseTestPage.TearDown() in c:\TeamCity\buildAgent\work\595bd9a420642936\MyClient\Solution\MyClient.UITests\BaseTestPage.cs:line 37
--DependencyResolutionException
at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters) in c:\ConsoleBuildAgent\work\f035b8dd08e41a61\src\TestStack.Seleno\Extensions\WebDriverExtensions.cs:line 0
at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters) in c:\ConsoleBuildAgent\work\f035b8dd08e41a61\src\TestStack.Seleno\Extensions\WebDriverExtensions.cs:line 0
at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters) in c:\ConsoleBuildAgent\work\f035b8dd08e41a61\src\TestStack.Seleno\Extensions\WebDriverExtensions.cs:line 0
at TestStack.Seleno.Configuration.AppConfigurator.CreateApplication() in c:\ConsoleBuildAgent\work\f035b8dd08e41a61\src\TestStack.Seleno\Configuration\AppConfigurator.cs:line 48
at TestStack.Seleno.Configuration.SelenoHost.Run(Action`1 configure) in c:\ConsoleBuildAgent\work\f035b8dd08e41a61\src\TestStack.Seleno\Configuration\SelenoHost.cs:line 83
--InvalidOperationException
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at MyClient.UITests.Host.PickWebDriver() in c:\TeamCity\buildAgent\work\595bd9a420642936\MyClient\Solution\MyClient.UITests\Host.cs:line 64
at System.Lazy`1.CreateValue()
at System.Lazy`1.LazyInitValue()
at TestStack.Seleno.Configuration.AppConfigurator.<>c__DisplayClassb.<WithRemoteWebDriver>b__8() in c:\ConsoleBuildAgent\work\f035b8dd08e41a61\src\TestStack.Seleno\Configuration\AppConfigurator.cs:line 84
at TestStack.Seleno.Configuration.AppConfigurator.<>c__DisplayClassf.<WithWebDriver>b__e(IComponentContext c) in c:\ConsoleBuildAgent\work\f035b8dd08e41a61\src\TestStack.Seleno\Configuration\AppConfigurator.cs:line 103
at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass1`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p) in c:\ConsoleBuildAgent\work\f035b8dd08e41a61\src\TestStack.Seleno\Extensions\WebDriverExtensions.cs:line 0
at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\ConsoleBuildAgent\work\f035b8dd08e41a61\src\TestStack.Seleno\Extensions\WebDriverExtensions.cs:line 0
at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\ConsoleBuildAgent\work\f035b8dd08e41a61\src\TestStack.Seleno\Extensions\WebDriverExtensions.cs:line 0
at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator) in c:\ConsoleBuildAgent\work\f035b8dd08e41a61\src\TestStack.Seleno\Extensions\WebDriverExtensions.cs:line 0
at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\ConsoleBuildAgent\work\f035b8dd08e41a61\src\TestStack.Seleno\Extensions\WebDriverExtensions.cs:line 0
at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\ConsoleBuildAgent\work\f035b8dd08e41a61\src\TestStack.Seleno\Extensions\WebDriverExtensions.cs:line 0
at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters) in c:\ConsoleBuildAgent\work\f035b8dd08e41a61\src\TestStack.Seleno\Extensions\WebDriverExtensions.cs:line 0
```

Am I right in assuming that it's something to do with the WebDriver we're using failing to start? I'm using Chrome Driver.

The strange thing is that if I retry the deployment it will sometimes pass, even if it takes a few retries.

**Comment by ArkSoftSystems** [comment]
Tengo el mismo problema
