### ISSUE TITLE
Could not find configured web driver; you need to embed an executable with the filename chromedriver.exe. 

### ISSUE THREAD

**Issue by justinhomes** [TestStack/TestStack.Seleno#260]
I am using
Chrome Version 58.0.3029.110 (64-bit)
VS 2015
**Nuget Pkg
    TestPack Version 0.9.6.1
    Selenium.WebDriver.ChromeDriver  Version 2.29
    Selenium.WebDriver  version 3.4
    Selenium.Support  version 3.4** 
Nuint 3.4
this is how i initialize my IISExpress

```
        Instance.Run("EMR.Web", 19456,
                configure => configure
                    .WithRemoteWebDriver(BrowserFactory.Chrome)
                    .UsingLoggerFactory(new ConsoleFactory())
            );
```

When this line executes, i get the error saying **chromerdriver.exe not found, but i can see it in bin folder of the test project that is running this UI test.**
```
IISExpressHost.Instance.NavigateToInitialPage<LoginPage>("/Account/Login");
```

```
System.TypeInitializationException : The type initializer for 'EMR.FunctionalTests.Infrastructure.IISExpressHost' threw an exception.
  ----> Autofac.Core.DependencyResolutionException : An exception was thrown while executing a resolve operation. See the InnerException for details. ---> Could not find configured web driver; you need to embed an executable with the filename chromedriver.exe. (See inner exception for details.)
  ----> TestStack.Seleno.Configuration.WebDriverNotFoundException : Could not find configured web driver; you need to embed an executable with the filename chromedriver.exe.
   at EMR.FunctionalTests.Navigation.GotoLoginPage() in D:\Home\CodeBack\EMR\Tests\EMR.FunctionalTests\Navigation.cs:line 11
   at EMR.FunctionalTests.Login.LoginTest.User_Can_Login_Sucessfully_With_Correct_Credentials() in D:\Home\CodeBack\EMR\Tests\EMR.FunctionalTests\Login\LoginTest.cs:line 14
--DependencyResolutionException
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters) in C:\ConsoleBuildAgent\work\6625a30e8ee728ba\src\TestStack.Seleno\Extensions\EnumerableExtensions.cs:line 0
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance) in C:\ConsoleBuildAgent\work\6625a30e8ee728ba\src\TestStack.Seleno\Extensions\EnumerableExtensions.cs:line 0
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters) in C:\ConsoleBuildAgent\work\6625a30e8ee728ba\src\TestStack.Seleno\Extensions\EnumerableExtensions.cs:line 0
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters) in C:\ConsoleBuildAgent\work\6625a30e8ee728ba\src\TestStack.Seleno\Extensions\EnumerableExtensions.cs:line 0
   at TestStack.Seleno.Configuration.SelenoApplication..ctor(IContainer container) in C:\ConsoleBuildAgent\work\6625a30e8ee728ba\src\TestStack.Seleno\Configuration\SelenoApplication.cs:line 36
   at TestStack.Seleno.Configuration.AppConfigurator.CreateApplication() in C:\ConsoleBuildAgent\work\6625a30e8ee728ba\src\TestStack.Seleno\Configuration\AppConfigurator.cs:line 49
   at TestStack.Seleno.Configuration.SelenoHost.CreateApplication(Action`1 configure) in C:\ConsoleBuildAgent\work\6625a30e8ee728ba\src\TestStack.Seleno\Configuration\SelenoHost.cs:line 104
   at TestStack.Seleno.Configuration.SelenoHost.Run(Action`1 configure) in C:\ConsoleBuildAgent\work\6625a30e8ee728ba\src\TestStack.Seleno\Configuration\SelenoHost.cs:line 0
   at EMR.FunctionalTests.Infrastructure.IISExpressHost..cctor() in D:\Home\CodeBack\EMR\Tests\EMR.FunctionalTests\Infrastructure\IISExpressHost.cs:line 12
--WebDriverNotFoundException
   at TestStack.Seleno.Configuration.WebDriverBuilder`1.EnsureFileExists(String resourceFileName) in C:\ConsoleBuildAgent\work\6625a30e8ee728ba\src\TestStack.Seleno\Configuration\WebDriverBuilder.cs:line 68
   at TestStack.Seleno.Configuration.WebDriverBuilder`1.Build() in C:\ConsoleBuildAgent\work\6625a30e8ee728ba\src\TestStack.Seleno\Configuration\WebDriverBuilder.cs:line 42
   at TestStack.Seleno.Configuration.BrowserFactory.Chrome() in C:\ConsoleBuildAgent\work\6625a30e8ee728ba\src\TestStack.Seleno\Configuration\BrowserFactory.cs:line 49
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass1`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p) in C:\ConsoleBuildAgent\work\6625a30e8ee728ba\src\TestStack.Seleno\Extensions\EnumerableExtensions.cs:line 0
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in C:\ConsoleBuildAgent\work\6625a30e8ee728ba\src\TestStack.Seleno\Extensions\EnumerableExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in C:\ConsoleBuildAgent\work\6625a30e8ee728ba\src\TestStack.Seleno\Extensions\EnumerableExtensions.cs:line 0
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator) in C:\ConsoleBuildAgent\work\6625a30e8ee728ba\src\TestStack.Seleno\Extensions\EnumerableExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.Execute() in C:\ConsoleBuildAgent\work\6625a30e8ee728ba\src\TestStack.Seleno\Extensions\EnumerableExtensions.cs:line 0
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in C:\ConsoleBuildAgent\work\6625a30e8ee728ba\src\TestStack.Seleno\Extensions\EnumerableExtensions.cs:line 0
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters) in C:\ConsoleBuildAgent\work\6625a30e8ee728ba\src\TestStack.Seleno\Extensions\EnumerableExtensions.cs:line 0

[Info] 'TestStack.Seleno.Configuration.AppConfigurator' Seleno v0.9.61.0, .NET Framework v4.0.30319.42000

```

**Comment by otaviosgoncalves** [comment]
Noone ?
